# ----- Dependencies

# GitHub is saying I shouldn't use `redcarpet` anymore
#markdown:         redcarpet
highlighter:      rouge

# ----- Permalinks
permalink:        pretty

# GitHub says relative_permalinks can't be used anymore
relative_permalinks: false

# ----- Setup
title:            John Gamboa
#tagline:          'Create something some day'
description:      ''
#url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'John Gamboa'
  url:            https://vaulttech.github.io

paginate:         5

# ----- Custom vars

#version:          2.1.0

github:            https://github.com/vaulttech/

